DROP TABLE OCEAN_DB;
CREATE TABLE OCEAN_DB 
   (	TARGET_CHEMBL_ID varchar(20) NOT NULL, 
	TARGET_PREF_NAME varchar(200) NOT NULL, 
	ORGANISM varchar(150) NOT NULL, 
	MOLREGNO integer NOT NULL,
	MOLECULE_CHEMBL_ID varchar(20) NOT NULL, 
	STANDARD_VALUE real NOT NULL,
	STANDARD_RELATION varchar(50) NOT NULL, 
	STANDARD_UNITS varchar(100) NOT NULL, 
	CANONICAL_SMILES varchar(4000) NOT NULL
  ) ;
  CREATE UNIQUE INDEX TMP_T_IDX1 ON OCEAN_DB (TARGET_CHEMBL_ID, MOLREGNO)   ;
  CREATE INDEX TMP_T_IDX2 ON OCEAN_DB (TARGET_CHEMBL_ID)   ;
  CREATE INDEX TMP_T_IDX3 ON OCEAN_DB (MOLREGNO)   ;
  CREATE INDEX TMP_T_IDX4 ON OCEAN_DB (TARGET_CHEMBL_ID, STANDARD_VALUE)   ;
  CREATE INDEX TMP_T_IDX5 ON OCEAN_DB (CANONICAL_SMILES) ;
