# Generated by Django 2.2.5 on 2019-11-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('id', models.AutoField(help_text='<< Primary Key >>', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('chembl_id', models.CharField(help_text='<< Primary Key >>', max_length=100, primary_key=True, serialize=False, verbose_name='chembl_id')),
                ('avr_fp', models.BinaryField(verbose_name='avr_fp')),
                ('num_cmpds', models.IntegerField(verbose_name='num_cmpds')),
                ('name', models.CharField(help_text='Name of Target', max_length=100, verbose_name='name')),
                ('compound_dict', models.BinaryField(verbose_name='avr_fp')),
            ],
        ),
        migrations.CreateModel(
            name='Rnd_set_comparison',
            fields=[
                ('id', models.AutoField(help_text='<< Primary Key >>', primary_key=True, serialize=False, verbose_name='id')),
                ('setsize', models.IntegerField(verbose_name='setsize')),
                ('fp', models.IntegerField(verbose_name='fp')),
                ('threshold', models.FloatField(default=0.0, help_text='Property Value', verbose_name='value')),
                ('rawscore', models.FloatField(default=0.0, verbose_name='rawscore')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.DataSources')),
            ],
        ),
        migrations.CreateModel(
            name='FP_Parameter',
            fields=[
                ('id', models.AutoField(help_text='<< Primary Key >>', primary_key=True, serialize=False, verbose_name='id')),
                ('fp_id', models.IntegerField(verbose_name='fp_id')),
                ('threshold', models.FloatField(default=0.0, verbose_name='value')),
                ('formula_raw_mean', models.CharField(max_length=100, verbose_name='formula_raw_mean')),
                ('formula_raw_stddev', models.CharField(max_length=100, verbose_name='formula_raw_stddev')),
                ('chisquare_mean', models.FloatField(default=0.0, verbose_name='chisquare_mean')),
                ('chisquare_evd', models.FloatField(default=0.0, verbose_name='chisquare_evd')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.DataSources')),
            ],
        ),
        migrations.CreateModel(
            name='All_FPS',
            fields=[
                ('id', models.AutoField(help_text='<< Primary Key >>', primary_key=True, serialize=False, verbose_name='id')),
                ('fp_id', models.IntegerField(verbose_name='fp_id')),
                ('fp_dict', models.BinaryField(verbose_name='fp_dict')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.DataSources')),
            ],
        ),
    ]
